project:
  type: website
  output-dir: site

website:
  title: "VVizarddev"

  navbar: false
  page-footer: false

format:
  html:
    theme: none
    css: styles.scss
    toc: false
    include-before-body:
      - partials/header.html
      - partials/ticker.html

execute:
  freeze: auto
